### ISSUE TITLE
DamageIndicatorHolograms bug

### ISSUE THREAD

**Issue by XXX10Tacles** [AzortisCode/ProtocolVanish#2]
hi, after installing plugin it bugged DamageIndicatorHolograms plaugin after showing me how much damage i did text was no longer disapiaring and when i was pick uping block or any item it was dropped on ground even if i wasnot using vanish. reconnecting was fixing problem.

**Comment by XXX10Tacles** [comment]
server is running CraftBukkit version git-Spigot-1a3504a-a46fdbc (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by JakeNijssen** [comment]
Thank you for noticing, I still have to add allot of API and hooks but I’ll make sure to add some hooks next update.

**Comment by JakeNijssen** [comment]
Ehm I cannot see any damage indicator holograms plugin only an outdated one from bukkit, can you please send me spigot page

**Comment by XXX10Tacles** [comment]
i dont remember where i got that plugin but i think i am using that one

**Comment by JakeNijssen** [comment]
Can you please check it for me, and if its the outdated one get a new one

**Comment by XXX10Tacles** [comment]
https://www.spigotmc.org/resources/damage-indicator-holograms.64432/

**Comment by JakeNijssen** [comment]
https://www.spigotmc.org/resources/damage-indicator-reborn.55974/ Use something like that, the one you send me has no single description etc so can't figure out on how to fix it for you

**Comment by XXX10Tacles** [comment]
okay thanks

**Comment by JakeNijssen** [comment]
Tell me if its fixed so I can close this issue

**Comment by XXX10Tacles** [comment]
that plugin wasnot working for me idk why so i used https://www.spigotmc.org/resources/ar-damage-holograms.46309/ this one and problem remeans.

**Comment by JakeNijssen** [comment]
https://www.spigotmc.org/resources/damage-indicator-reborn.55974/ that one?

**Comment by JakeNijssen** [comment]
Also that one doesn't support 1.13 so its not my fault

**Comment by XXX10Tacles** [comment]
okay

**Comment by JakeNijssen** [comment]
did it work the one I send?
