### ISSUE TITLE
GeneralEntity Listener Causes Ghost Entities (Items) to Often Appear

### ISSUE THREAD

**Issue by ghost** [AzortisCode/ProtocolVanish#5]
Server: 1.15.2 Paper
Plugins: ProtocolLib, ProtocolVanish, PlaceholderAPI

Tested by summoning a surplus amount of zombies then killing them and then their items. Commenting out GeneralEntity from the config and restarting the server fixes the issue.

**Comment by JakeNijssen** [comment]
Hey there, sorry for late response have been on vacation. This issue also seems to bug me allot of the times, can you try using the latest protocollib build from: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
tell me how it went.

**Comment by JakeNijssen** [comment]
Solved in latest v0.5
